---
- name: Ensuring config directories exist
  file:
    path: "{{ nfs_ganesha_ceph_config_dir }}"
    state: directory
    mode: "0770"
  become: yes

- name: Copying over config.json files for service
  template:
    src: "config.json.j2"
    dest: "{{ nfs_ganesha_ceph_config_dir }}/config.json"
    mode: "0660"
  become: yes

- name: Copying over ganesha.conf
  template:
    src: "ganesha.conf.j2"
    dest: "{{ nfs_ganesha_ceph_config_dir }}/ganesha.conf"
    mode: "0600"
  become: yes
  
- name: Starting nfs-ganesha-ceph container
  become: true
  kolla_docker:
    action: "start_container"
    common_options: "{{ docker_common_options }}"
    image: "{{ kolla_nfs_ganesha_ceph_image_full }}"
    name: "nfs_ganesha_ceph"
    volumes:
      - "{{ nfs_ganesha_ceph_config_dir }}:{{ container_config_directory }}/:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - "kolla_logs:/var/log/kolla/"
